apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: documentserver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: documentserver
          servicePort: 8888
      - path: /example
        backend:
          serviceName: example
          servicePort: 8888