apiVersion: batch/v1
kind: Job
metadata:
  name: prepare4update
spec:
  template:
    spec:
      volumes:
        - name: ds-files
          persistentVolumeClaim:
            claimName: ds-files
        - name: remove-db-scripts
          configMap: 
            name: remove-db-scripts
        - name: init-db-scripts
          configMap:
            name: init-db-scripts
      containers:
        - name: prepare4update
          image: postgres
          envFrom:
          - configMapRef:
              name: documentserver
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          volumeMounts:
          - name: ds-files
            mountPath: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - name: remove-db-scripts
            mountPath: /sql/removetbl.sql
            subPath: removetbl.sql
          - name: init-db-scripts
            mountPath: /sql/createdb.sql
            subPath: createdb.sql

          command: ["/bin/bash"]
          args:
            - -c
            - >
              apt update && apt -y install curl;
              curl -v http://docservice:8000/internal/cluster/inactive -X PUT -s -o /dev/null; 

              FILES_DIR=/var/lib/onlyoffice/documentserver/App_Data/cache/files;
              BACKUP_DIR=backup/$(date +"%d_%m_%Y");
              mkdir -p $FILES_DIR/$BACKUP_DIR/files;
              chown -R 101 $FILES_DIR/backup;

              for ENTRY in `ls $FILES_DIR`; do
                case $ENTRY in

                  errors)
                    ;;

                  forgotten)
                    ;;

                  backup)
                    ;;

                  *)
                  mv -v $FILES_DIR/$ENTRY $FILES_DIR/$BACKUP_DIR/files/
                    ;;
                esac;
              done;

              PGPASSWORD=$DB_PWD pg_dump --host=$DB_HOST --user=$DB_USER -F c $DB_USER > $FILES_DIR/$BACKUP_DIR/backup_$(date +"%d_%m_%Y_%H:%M").dump;
              
              PGPASSWORD=$DB_PWD psql --host=$DB_HOST --user=$DB_USER --file=/sql/removetbl.sql;
              PGPASSWORD=$DB_PWD psql --host=$DB_HOST --user=$DB_USER --file=/sql/createdb.sql;

              echo work done;

      restartPolicy: Never
