apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db
      image: onlyoffice/4testing-ds-db:latest
      env:
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: documentserver
            key: DB_NAME
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: documentserver
            key: DB_USER
      - name: POSTGRES_HOST_AUTH_METHOD
        value: trust
      ports:
      - containerPort: 5432